<a href="https://colab.research.google.com/github/ldsAS/Tibame-AI-Learning/blob/main/Tibame20250502_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas
* https://pandas.pydata.org/
* https://pandas.pydata.org/docs/

### 說明
* 不同於Numpy是用來進行單純的數值分析，大部分的資料會包含異質資料型態的欄位。<BR>[參考：R公司_人員資料.xlsx]
* Pandas是Python 中非常流行的一個數據分析庫，它為數據操作、清理和分析提供了強大的功能。<BR>
* Pandas基於Numpy架構了Dataframe，可以方便的處理資料表(Table)

### 典型應用場景：
* 數據分析和可視化
* 數據清理（例如處理缺失值、重複數據等）
* 數據預處理（例如標準化、歸一化）
* 大規模數據的聚合、篩選、分組等操作

In [ ]:
! pip install pandas openpyxl

In [1]:
import numpy as np
import pandas as pd

In [44]:
# 讀取Excel資料(路徑是自己資料夾的相對路徑)
# data = pd.read_excel('../data/R公司_人員資料.xlsx',engine='openpyxl')

# 亦可用/content放到colab本身的資料夾，
data = pd.read_excel('../content/Test/R公司_人員資料.xlsx',engine='openpyxl')

# 或是直接掛Google硬碟的路徑(要import drive)
# data = pd.read_excel('/content/drive/MyDrive/*職訓/資料分析/Data/R公司_人員資料.xlsx',engine='openpyxl')

# 絕對路徑若設在windows的資料夾，使用[「反斜線」改寫路徑
# data = pd.read_excel('..\data\R公司_人員資料.xlsx',engine='openpyxl')

# 使用 head() 讀前五行，查看是否讀取成功
data.head()

,員工編號(EmployeeNumber),性別(Gender),年齡(Age),是否為成年人(Over18),婚姻狀態(MaritalStatus),通勤距離(DistanceFromHome),教育程度(Education),教育專業領域(EducationField),部門(Department),職位名稱(JobRole),...,股票選擇權等級(StockOptionLevel),績效評估(PerformanceRating),出差頻率(BusinessTravel),去年訓練時間(TrainingTimesLastYear),工作滿意度(JobSatisfaction),工作環境滿意度(EnvironmentSatisfaction),工作投入(JobInvolvement),工作生活平衡(WorkLifeBalance),人際關係滿意度(RelationshipSatisfaction),離職(Attrition)
0,1,Female,41,Y,Single,1,2,Life Sciences,Sales,Sales Executive,...,0,3,Travel_Rarely,0,4,2,3,1,1,Yes
1,2,Male,49,Y,Married,8,1,Life Sciences,Research & Development,Research Scientist,...,1,4,Travel_Frequently,3,2,3,2,3,4,No
2,4,Male,37,Y,Single,2,2,Other,Research & Development,Laboratory Technician,...,0,3,Travel_Rarely,3,3,4,2,3,2,Yes
3,5,Female,33,Y,Married,3,4,Life Sciences,Research & Development,Research Scientist,...,0,3,Travel_Frequently,3,3,4,3,3,3,No
4,7,Male,27,Y,Married,2,1,Medical,Research & Development,Laboratory Technician,...,1,3,Travel_Rarely,3,2,1,3,3,4,No

In [19]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
data = pd.read_excel('/content/drive/MyDrive/*職訓/資料分析/Data/R公司_人員資料.xlsx',engine='openpyxl')
data.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,員工編號(EmployeeNumber),性別(Gender),年齡(Age),是否為成年人(Over18),婚姻狀態(MaritalStatus),通勤距離(DistanceFromHome),教育程度(Education),教育專業領域(EducationField),部門(Department),職位名稱(JobRole),...,股票選擇權等級(StockOptionLevel),績效評估(PerformanceRating),出差頻率(BusinessTravel),去年訓練時間(TrainingTimesLastYear),工作滿意度(JobSatisfaction),工作環境滿意度(EnvironmentSatisfaction),工作投入(JobInvolvement),工作生活平衡(WorkLifeBalance),人際關係滿意度(RelationshipSatisfaction),離職(Attrition)
0,1,Female,41,Y,Single,1,2,Life Sciences,Sales,Sales Executive,...,0,3,Travel_Rarely,0,4,2,3,1,1,Yes
1,2,Male,49,Y,Married,8,1,Life Sciences,Research & Development,Research Scientist,...,1,4,Travel_Frequently,3,2,3,2,3,4,No
2,4,Male,37,Y,Single,2,2,Other,Research & Development,Laboratory Technician,...,0,3,Travel_Rarely,3,3,4,2,3,2,Yes
3,5,Female,33,Y,Married,3,4,Life Sciences,Research & Development,Research Scientist,...,0,3,Travel_Frequently,3,3,4,3,3,3,No
4,7,Male,27,Y,Married,2,1,Medical,Research & Development,Laboratory Technician,...,1,3,Travel_Rarely,3,2,1,3,3,4,No

# Series
維數據結構，類似於 Python 中的列表或 NumPy 的數組，通常用來表示一列數據。

In [9]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [ ]:
# 底層是用Numpy來實作
data.values

### 讀取資料的方式會跟Numpy相似

In [ ]:
data[1]
data

In [ ]:
data[1:3]

## 設定索引

In [21]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [26]:
data['b']

np.float64(0.5)

In [ ]:
# 練習題
# 請試著建立一個Seriers物件，內容值為五個人的身高。並使用人名當成索引。
# 身高 = ...........

### 索引也可以是數值

In [ ]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=[2, 5, 3, 7])
data

In [ ]:
data[2]

In [ ]:
# 問題
# 如果出現不存在的索引會怎樣？

### 可以使用python中的dict來建立資料

In [27]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [28]:
population['California']

np.int64(38332521)

In [29]:
population['California':'Illinois']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

↑雖然可以這樣做，但是強烈建議不要

In [ ]:
# 練習題
# 請改用dict來建立身高與姓名對應的Series

### 幾種不同建構Serier物件的方式

In [30]:
pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

In [31]:
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [32]:
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

In [33]:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2])

3    c
2    a
dtype: object

# DataFrame
二維數據結構，類似於 Excel 表格或 SQL 數據表，是 Pandas 中最常用的數據結構。它由多個 Series 組成，每個 Series 代表一列。

In [34]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)

area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [35]:
states = pd.DataFrame({'人口': population,
                       '面積': area})
states

                  人口      面積
California  38332521  423967
Texas       26448193  695662
New York    19651127  141297
Florida     19552860  170312
Illinois    12882135  149995

In [39]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [37]:
states.columns

Index(['人口', '面積'], dtype='object')

In [38]:
# 練習題
# 請建立另一個體重與姓名關係的Series
# 並再建立一個包含 體重與身高 的 DataFrame,使用姓名當索引
height = pd.Series([162, 175, 177, 155, 168],
                   index=['Ken', 'Mary', 'David', 'Emmy', 'Frank'])
weight = pd.Series([80, 55, 70, 45, 63],
                   index=['Ken', 'Mary', 'David', 'Emmy', 'Frank'])

person = pd.DataFrame({'身高':height, '體重':weight})
person

        身高  體重
Ken    162  80
Mary   175  55
David  177  70
Emmy   155  45
Frank  168  63

In [40]:
#取得特定欄位的資料
states['面積']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: 面積, dtype: int64

In [41]:
# 檢查是否包含某個索引
'Texas' in states.index

True

## 從檔案載入資料

In [43]:
# iris = pd.read_csv('../data/Iris.csv')
iris = pd.read_csv('../content/Test/Iris.csv')
iris

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [45]:
#快速查看前幾筆資料
iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [46]:
iris[2:6]

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa

In [47]:
iris['SepalLengthCm']

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: SepalLengthCm, Length: 150, dtype: float64

In [48]:
iris['SepalLengthCm'][2:6]

2    4.7
3    4.6
4    5.0
5    5.4
Name: SepalLengthCm, dtype: float64

In [49]:
iris[2:6]['SepalLengthCm']

2    4.7
3    4.6
4    5.0
5    5.4
Name: SepalLengthCm, dtype: float64

#### 取出部分資料的方法

In [ ]:
# 這樣會失敗
iris[[2,4,7,9]]

In [51]:
#正確方式，使用loc要多包一層[]
iris.loc[[2,4,7,9]]

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
2   3            4.7           3.2            1.3           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
7   8            5.0           3.4            1.5           0.2  Iris-setosa
9  10            4.9           3.1            1.5           0.1  Iris-setosa

#### 練習題用資料

In [53]:
h = {'David':162, 'Ken':169, 'Sam': 173, 'Owen':165, 'Paul':177}
w = {'David':70, 'Owen':80, 'Paul':78, 'Ken':65, 'Sam': 83}
person = pd.DataFrame({'身高': h, '體重': w})
person

        身高  體重
David  162  70
Ken    169  65
Sam    173  83
Owen   165  80
Paul   177  78

In [ ]:
#練習題
#請列出第 1~3 筆資料

In [ ]:
# 列出第 2,4,5筆資料
# 下面的寫法為何失敗？
person.loc[[1,3,4]]

In [54]:
person.iloc[[1,3,4]]

       身高  體重
Ken   169  65
Owen  165  80
Paul  177  78

In [56]:
person.loc[['Ken','Owen','Paul']]

       身高  體重
Ken   169  65
Owen  165  80
Paul  177  78

### 問題： loc 跟 iloc 有什麼不同？
```
data.loc[XXXXX]  <- XXXX裡面是填index
data.iloc[XXXXX] <- XXXX裡面是填資料的絕對位置(數字)
```

In [ ]:
person['身高']

In [ ]:
person.身高

In [ ]:
for i in range

In [59]:
# 練習題
# 猜猜如何將算出來的 BMI 變成新欄位併入原始資料表中
x = person.體重 / ((person.身高/100)**2)
person['BMI'] = x
person

        身高  體重        BMI
David  162  70  26.672763
Ken    169  65  22.758307
Sam    173  83  27.732300
Owen   165  80  29.384757
Paul   177  78  24.897060

In [60]:
# 練習題
# 請使用前面練習的個人資料，查詢並列出 BMI > 24的人
person.loc[ person['BMI'] > 24 ]

        身高  體重        BMI
David  162  70  26.672763
Sam    173  83  27.732300
Owen   165  80  29.384757
Paul   177  78  24.897060

# 查詢

In [ ]:
iris[iris.SepalLengthCm > 5]

In [ ]:
iris.SepalLengthCm > 5

In [ ]:
iris['Species'][iris.SepalLengthCm > 5]

In [ ]:
iris[iris.SepalLengthCm > 5]['Species']

In [ ]:
# 練習題
# 請使用前面練習的個人資料，查詢並列出 BMI > 24的人
person.loc[ person.BMI > 24 ]

#### 兩個欄位結合成一個資料表時，缺失的資料會以NaN來表示

In [69]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127}, name='population')
states = pd.DataFrame({'population': population,
                       'area': area})
states

            population       area
Alaska             NaN  1723337.0
California  38332521.0   423967.0
New York    19651127.0        NaN
Texas       26448193.0   695662.0

In [70]:
# 正確改變查詢結果切片值的方法
person2 = person.copy()
person2.loc[person2.BMI > 24, '身高'] = 100
person2

        身高  體重        BMI
David  100  70  26.672763
Ken    169  65  22.758307
Sam    100  83  27.732300
Owen   100  80  29.384757
Paul   100  78  24.897060

# 其他功能

In [63]:
# data = pd.read_excel('../data/R公司_人員資料.xlsx',engine='openpyxl')
data = pd.read_excel('../content/Test/R公司_人員資料.xlsx',engine='openpyxl')
data.head()

,員工編號(EmployeeNumber),性別(Gender),年齡(Age),是否為成年人(Over18),婚姻狀態(MaritalStatus),通勤距離(DistanceFromHome),教育程度(Education),教育專業領域(EducationField),部門(Department),職位名稱(JobRole),...,股票選擇權等級(StockOptionLevel),績效評估(PerformanceRating),出差頻率(BusinessTravel),去年訓練時間(TrainingTimesLastYear),工作滿意度(JobSatisfaction),工作環境滿意度(EnvironmentSatisfaction),工作投入(JobInvolvement),工作生活平衡(WorkLifeBalance),人際關係滿意度(RelationshipSatisfaction),離職(Attrition)
0,1,Female,41,Y,Single,1,2,Life Sciences,Sales,Sales Executive,...,0,3,Travel_Rarely,0,4,2,3,1,1,Yes
1,2,Male,49,Y,Married,8,1,Life Sciences,Research & Development,Research Scientist,...,1,4,Travel_Frequently,3,2,3,2,3,4,No
2,4,Male,37,Y,Single,2,2,Other,Research & Development,Laboratory Technician,...,0,3,Travel_Rarely,3,3,4,2,3,2,Yes
3,5,Female,33,Y,Married,3,4,Life Sciences,Research & Development,Research Scientist,...,0,3,Travel_Frequently,3,3,4,3,3,3,No
4,7,Male,27,Y,Married,2,1,Medical,Research & Development,Laboratory Technician,...,1,3,Travel_Rarely,3,2,1,3,3,4,No

### 排序

In [64]:
# 針對年齡欄位排序
data.sort_values(by='年齡(Age)', ascending=False)

,員工編號(EmployeeNumber),性別(Gender),年齡(Age),是否為成年人(Over18),婚姻狀態(MaritalStatus),通勤距離(DistanceFromHome),教育程度(Education),教育專業領域(EducationField),部門(Department),職位名稱(JobRole),...,股票選擇權等級(StockOptionLevel),績效評估(PerformanceRating),出差頻率(BusinessTravel),去年訓練時間(TrainingTimesLastYear),工作滿意度(JobSatisfaction),工作環境滿意度(EnvironmentSatisfaction),工作投入(JobInvolvement),工作生活平衡(WorkLifeBalance),人際關係滿意度(RelationshipSatisfaction),離職(Attrition)
1209,1697,Male,60,Y,Divorced,1,4,Medical,Research & Development,Healthcare Representative,...,1,4,Travel_Rarely,2,4,3,1,4,3,No
411,549,Female,60,Y,Married,7,3,Life Sciences,Research & Development,Manager,...,0,3,Travel_Rarely,5,1,1,3,1,4,No
427,573,Female,60,Y,Married,28,3,Marketing,Sales,Sales Executive,...,0,3,Travel_Frequently,5,1,3,2,4,4,No
879,1233,Male,60,Y,Divorced,7,4,Marketing,Sales,Sales Executive,...,1,3,Travel_Rarely,3,4,2,4,3,2,No
536,732,Male,60,Y,Single,16,4,Marketing,Sales,Sales Executive,...,0,3,Travel_Rarely,1,1,1,3,3,4,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
296,405,Male,18,Y,Single,3,3,Life Sciences,Research & Development,Laboratory Technician,...,0,3,Travel_Rarely,2,3,3,3,3,3,Yes
301,411,Female,18,Y,Single,10,3,Medical,Sales,Sales Representative,...,0,3,Travel_Rarely,2,3,4,2,3,1,No
727,1012,Male,18,Y,Single,5,2,Life Sciences,Research & Development,Research Scientist,...,0,3,Non-Travel,2,4,2,3,3,4,No
1153,1624,Female,18,Y,Single,3,2,Medical,Sales,Sales Representative,...,0,3,Travel_Frequently,2,4,2,3,4,3,Yes
457,614,Male,18,Y,Single,5,3,Marketing,Sales,Sales Representative,...,0,3,Travel_Frequently,3,2,2,3,3,4,Yes

### 取值

In [ ]:
# 找出部門欄位裡有多少個不同的值？
data['部門(Department)'].unique()

array(['Sales', 'Research & Development', 'Human Resources'], dtype=object)

### 統計

In [ ]:
#列出所有數值欄位的基本統計數據
data.describe()

,員工編號(EmployeeNumber),年齡(Age),通勤距離(DistanceFromHome),教育程度(Education),職位等級(JobLevel),在該公司工作總年資(YearsAtCompany),在該職位工作年資(YearsInCurrentRole),在該職等工作年資(YearsSinceLastPromotion),與現任管理者工作年資(YearsWithCurrManager),總工作年資(TotalWorkingYears),...,標準工作時間(StandardHours),調薪百分比(PercentSalaryHike),股票選擇權等級(StockOptionLevel),績效評估(PerformanceRating),去年訓練時間(TrainingTimesLastYear),工作滿意度(JobSatisfaction),工作環境滿意度(EnvironmentSatisfaction),工作投入(JobInvolvement),工作生活平衡(WorkLifeBalance),人際關係滿意度(RelationshipSatisfaction)
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,...,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,1024.865306,36.923810,9.192517,2.912925,2.063946,7.008163,4.229252,2.187755,4.123129,11.279592,...,80.0,15.209524,0.793878,3.153741,2.799320,2.728571,2.721769,2.729932,2.761224,2.712245
std,602.024335,9.135373,8.106864,1.024165,1.106940,6.126525,3.623137,3.222430,3.568136,7.780782,...,0.0,3.659938,0.852077,0.360824,1.289271,1.102846,1.093082,0.711561,0.706476,1.081209
min,1.000000,18.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,80.0,11.000000,0.000000,3.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,491.250000,30.000000,2.000000,2.000000,1.000000,3.000000,2.000000,0.000000,2.000000,6.000000,...,80.0,12.000000,0.000000,3.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000
50%,1020.500000,36.000000,7.000000,3.000000,2.000000,5.000000,3.000000,1.000000,3.000000,10.000000,...,80.0,14.000000,1.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000
75%,1555.750000,43.000000,14.000000,4.000000,3.000000,9.000000,7.000000,3.000000,7.000000,15.000000,...,80.0,18.000000,1.000000,3.000000,3.000000,4.000000,4.000000,3.000000,3.000000,4.000000
max,2068.000000,60.000000,29.000000,5.000000,5.000000,40.000000,18.000000,15.000000,17.000000,40.000000,...,80.0,25.000000,3.000000,4.000000,6.000000,4.000000,4.000000,4.000000,4.000000,4.000000

In [ ]:
#列出所有欄位的基本統計數據
data.describe(include='all')

,員工編號(EmployeeNumber),性別(Gender),年齡(Age),是否為成年人(Over18),婚姻狀態(MaritalStatus),通勤距離(DistanceFromHome),教育程度(Education),教育專業領域(EducationField),部門(Department),職位名稱(JobRole),...,股票選擇權等級(StockOptionLevel),績效評估(PerformanceRating),出差頻率(BusinessTravel),去年訓練時間(TrainingTimesLastYear),工作滿意度(JobSatisfaction),工作環境滿意度(EnvironmentSatisfaction),工作投入(JobInvolvement),工作生活平衡(WorkLifeBalance),人際關係滿意度(RelationshipSatisfaction),離職(Attrition)
count,1470.000000,1470,1470.000000,1470,1470,1470.000000,1470.000000,1470,1470,1470,...,1470.000000,1470.000000,1470,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470
unique,NaN,2,NaN,1,3,NaN,NaN,6,3,9,...,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,2
top,NaN,Male,NaN,Y,Married,NaN,NaN,Life Sciences,Research & Development,Sales Executive,...,NaN,NaN,Travel_Rarely,NaN,NaN,NaN,NaN,NaN,NaN,No
freq,NaN,882,NaN,1470,673,NaN,NaN,606,961,326,...,NaN,NaN,1043,NaN,NaN,NaN,NaN,NaN,NaN,1233
mean,1024.865306,NaN,36.923810,NaN,NaN,9.192517,2.912925,NaN,NaN,NaN,...,0.793878,3.153741,NaN,2.799320,2.728571,2.721769,2.729932,2.761224,2.712245,NaN
std,602.024335,NaN,9.135373,NaN,NaN,8.106864,1.024165,NaN,NaN,NaN,...,0.852077,0.360824,NaN,1.289271,1.102846,1.093082,0.711561,0.706476,1.081209,NaN
min,1.000000,NaN,18.000000,NaN,NaN,1.000000,1.000000,NaN,NaN,NaN,...,0.000000,3.000000,NaN,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,NaN
25%,491.250000,NaN,30.000000,NaN,NaN,2.000000,2.000000,NaN,NaN,NaN,...,0.000000,3.000000,NaN,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,NaN
50%,1020.500000,NaN,36.000000,NaN,NaN,7.000000,3.000000,NaN,NaN,NaN,...,1.000000,3.000000,NaN,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,NaN
75%,1555.750000,NaN,43.000000,NaN,NaN,14.000000,4.000000,NaN,NaN,NaN,...,1.000000,3.000000,NaN,3.000000,4.000000,4.000000,3.000000,3.000000,4.000000,NaN
max,2068.000000,NaN,60.000000,NaN,NaN,29.000000,5.000000,NaN,NaN,NaN,...,3.000000,4.000000,NaN,6.000000,4.000000,4.000000,4.000000,4.000000,4.000000,NaN

In [ ]:
#取得年齡的標準差
data['年齡(Age)'].std()

np.float64(9.135373489136732)

In [ ]:
#計算年資與年齡的相關性
data['年齡(Age)'].corr(data['總工作年資(TotalWorkingYears)'])

np.float64(0.6803805357911985)

In [ ]:
#檢查是否有空值
data['年齡(Age)'].hasnans

False

In [65]:
#列出全部欄位的缺失值數量
data.isnull().sum()

員工編號(EmployeeNumber)                 0
性別(Gender)                           0
年齡(Age)                              0
是否為成年人(Over18)                       0
婚姻狀態(MaritalStatus)                  0
通勤距離(DistanceFromHome)               0
教育程度(Education)                      0
教育專業領域(EducationField)               0
部門(Department)                       0
職位名稱(JobRole)                        0
職位等級(JobLevel)                       0
在該公司工作總年資(YearsAtCompany)            0
在該職位工作年資(YearsInCurrentRole)         0
在該職等工作年資(YearsSinceLastPromotion)    0
與現任管理者工作年資(YearsWithCurrManager)     0
總工作年資(TotalWorkingYears)             0
過去工作公司家數(NumCompaniesWorked)         0
每日工資額(DailyRate)                     0
每小時工資額(HourlyRate)                   0
月收入(MonthlyIncome)                   0
月費率(MonthlyRate)                     0
標準工作時間(StandardHours)                0
加班(OverTime)                         0
調薪百分比(PercentSalaryHike)             0
股票選擇權等級(StockOptionLevel)            0
績效評估(PerformanceRating)              0
出差頻率(BusinessTravel)                 0
去年訓練時間(TrainingTimesLastYear)        0
工作滿意度(JobSatisfaction)               0
工作環境滿意度(EnvironmentSatisfaction)     0
工作投入(JobInvolvement)                 0
工作生活平衡(WorkLifeBalance)              0
人際關係滿意度(RelationshipSatisfaction)    0
離職(Attrition)                        0
dtype: int64

In [66]:
# 檢查資料欄位的型態，以及缺失狀況
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 34 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   員工編號(EmployeeNumber)               1470 non-null   int64
 1   性別(Gender)                         1470 non-null   object
 2   年齡(Age)                            1470 non-null   int64
 3   是否為成年人(Over18)                     1470 non-null   object
 4   婚姻狀態(MaritalStatus)                1470 non-null   object
 5   通勤距離(DistanceFromHome)             1470 non-null   int64
 6   教育程度(Education)                    1470 non-null   int64
 7   教育專業領域(EducationField)             1470 non-null   object
 8   部門(Department)                     1470 non-null   object
 9   職位名稱(JobRole)                      1470 non-null   object
 10  職位等級(JobLevel)                     1470 non-null   int64
 11  在該公司工作總年資(YearsAtCompany)          1470 non-null   int64
 12  在該職位工作年資(YearsInCurrentRole)       1470 non-null   int64
 13  在該職等工作年資(YearsSinceLastPromotion)  1470 non-null   int64
 14  與現任管理者工作年資(YearsWithCurrManager)   1470 non-null   int64
 15  總工作年資(TotalWorkingYears)           1470 non-null   int64
 16  過去工作公司家數(NumCompaniesWorked)       1470 non-null   int64
 17  每日工資額(DailyRate)                   1470 non-null   int64
 18  每小時工資額(HourlyRate)                 1470 non-null   int64
 19  月收入(MonthlyIncome)                 1470 non-null   int64
 20  月費率(MonthlyRate)                   1470 non-null   int64
 21  標準工作時間(StandardHours)              1470 non-null   int64
 22  加班(OverTime)                       1470 non-null   object
 23  調薪百分比(PercentSalaryHike)           1470 non-null   int64
 24  股票選擇權等級(StockOptionLevel)          1470 non-null   int64
 25  績效評估(PerformanceRating)            1470 non-null   int64
 26  出差頻率(BusinessTravel)               1470 non-null   object
 27  去年訓練時間(TrainingTimesLastYear)      1470 non-null   int64
 28  工作滿意度(JobSatisfaction)             1470 non-null   int64
 29  工作環境滿意度(EnvironmentSatisfaction)   1470 non-null   int64
 30  工作投入(JobInvolvement)               1470 non-null   int64
 31  工作生活平衡(WorkLifeBalance)            1470 non-null   int64
 32  人際關係滿意度(RelationshipSatisfaction)  1470 non-null   int64
 33  離職(Attrition)                      1470 non-null   object
dtypes: int64(25), object(9)
memory usage: 390.6+ KB

In [67]:
#查看資料筆數跟欄位數目
data.shape

(1470, 34)

In [68]:
#計算欄位值總數
data['部門(Department)'].value_counts()

部門(Department)
Research & Development    961
Sales                     446
Human Resources            63
Name: count, dtype: int64