<a href="https://colab.research.google.com/github/ldsAS/Tibame-AI-Learning/blob/main/Tibame20250502_Pandas_%E8%AA%B2%E5%A0%82%E7%B7%B4%E7%BF%92.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* 完成後請寄到EMAIL : clement.class.02@gmail.com
* 信件主旨請設定為： 03-02.Pandas_課堂練習_學號_姓名 (例: "03-02.Pandas_課堂練習_00_陳仁政")
* 附件檔名請設定為： 03-02.Pandas_課堂練習_學號_姓名.ipynb (例: "03-02.Pandas_課堂練習_00_陳仁政.ipynb")

In [24]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv("../content/Test/vgsales.csv")
data.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

In [25]:
data.shape

(16598, 11)

In [10]:
# 找出有缺失值的欄位
data.isnull().sum()
# 或是用info(需自行比對總數)
# data.info()

Rank              0
Name              0
Platform          0
Year            271
Genre             0
Publisher        58
NA_Sales          0
EU_Sales          0
JP_Sales          0
Other_Sales       0
Global_Sales      0
dtype: int64

In [12]:
# 計算欄位的基本統計數據
data.describe()

,Rank,Year,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
count,16598.000000,16327.000000,16598.000000,16598.000000,16598.000000,16598.000000,16598.000000
mean,8300.605254,2006.406443,0.264667,0.146652,0.077782,0.048063,0.537441
std,4791.853933,5.828981,0.816683,0.505351,0.309291,0.188588,1.555028
min,1.000000,1980.000000,0.000000,0.000000,0.000000,0.000000,0.010000
25%,4151.250000,2003.000000,0.000000,0.000000,0.000000,0.000000,0.060000
50%,8300.500000,2007.000000,0.080000,0.020000,0.000000,0.010000,0.170000
75%,12449.750000,2010.000000,0.240000,0.110000,0.040000,0.040000,0.470000
max,16600.000000,2020.000000,41.490000,29.020000,10.220000,10.570000,82.740000

In [13]:
# 取出 "Publisher" 欄位的資料
data["Publisher"]

0          Nintendo
1          Nintendo
2          Nintendo
3          Nintendo
4          Nintendo
            ...
16593         Kemco
16594    Infogrames
16595    Activision
16596      7G//AMES
16597       Wanadoo
Name: Publisher, Length: 16598, dtype: object

In [14]:
# 取出 Publisher, Name, Genre 欄位的資料
data[["Publisher", "Name", "Genre"]]

,Publisher,Name,Genre
0,Nintendo,Wii Sports,Sports
1,Nintendo,Super Mario Bros.,Platform
2,Nintendo,Mario Kart Wii,Racing
3,Nintendo,Wii Sports Resort,Sports
4,Nintendo,Pokemon Red/Pokemon Blue,Role-Playing
...,...,...,...
16593,Kemco,Woody Woodpecker in Crazy Castle 5,Platform
16594,Infogrames,Men in Black II: Alien Escape,Shooter
16595,Activision,SCORE International Baja 1000: The Official Game,Racing
16596,7G//AMES,Know How 2,Puzzle
16597,Wanadoo,Spirits & Spells,Platform

In [22]:
# 計算每筆資料的 NA_Sales,EU_Sales,JP_Sales,Other_Sales 總和
data[['NA_Sales', "EU_Sales", "JP_Sales", "Other_Sales"]].sum(axis=1)

0        82.74
1        40.24
2        35.83
3        33.00
4        31.38
         ...
16593     0.01
16594     0.01
16595     0.00
16596     0.01
16597     0.01
Length: 16598, dtype: float64

In [20]:
# 另一個寫法(使用sum的方式較佳)
data["NA_Sales"]+data["EU_Sales"]+data["JP_Sales"]+data["Other_Sales"]

0        82.74
1        40.24
2        35.83
3        33.00
4        31.38
         ...
16593     0.01
16594     0.01
16595     0.00
16596     0.01
16597     0.01
Length: 16598, dtype: float64

In [23]:
# 計算每筆資料的 NA_Sales,EU_Sales,JP_Sales,Other_Sales 總和，並存入新的欄位"總和"
data["總和"] = data[['NA_Sales', "EU_Sales", "JP_Sales", "Other_Sales"]].sum(axis=1)
data.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,總和
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,35.83
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,31.38

In [ ]:
#找出發行商為Nintendo的遊戲名稱

In [ ]:
#列出所有Wii的遊戲名稱

In [ ]:
#計算所有GBA遊戲的銷售總合

In [ ]:
#計算任天堂運動類遊戲的銷售總量

In [ ]:
#列出北美地區銷售量最高的前五名遊戲

In [ ]:
#列出北美與歐洲地區銷售量總和最高的前五名遊戲

In [ ]:
#找出總共有多少種不同的平台

In [ ]:
#寫程式計算不同平台的總銷售量

In [ ]:
# 使用GroupBy來完成上述的工作